### ISSUE TITLE
Option to work in user mode

### ISSUE THREAD

**Issue by Real-Gecko** [lxc/terraform-provider-incus#106]
I've currently reinstalled Incus and switched to work in fully [user mode](https://wiki.archlinux.org/title/Incus#Accessing_Incus_as_an_unprivileged_user) with `incus-user.socket`. The provider however still tries to work through `incus.socket`. I can fix the issue with environment variable `INCUS_SOCKET=/var/lib/incus/unix.socket.user`, but it would be nice to have an option on provider level to work with user socket without environment variables, something like:
```terraform
provider "incus" {
    user_socket = true
}
```

**Comment by stgraber** [comment]
We should probably just ensure it does the fallback to the local socket the same way the CLI does.

**Comment by maveonair** [comment]
This should have been fixed with https://github.com/lxc/terraform-provider-incus/pull/65. But I am not sure if we have released that yet in a version.

**Comment by Real-Gecko** [comment]
Ah, great, thank you! Will wait for new release.
