### ISSUE TITLE
Bug: Image resources fail for OCI image source

### ISSUE THREAD

**Issue by bketelsen** [lxc/terraform-provider-incus#108]
With an OCI remote configured, the provider fails to retrieve Incus Image server:

```
resource "incus_image" "postgres" {
  source_remote = "docker"
  source_image  = "postgres"
}
```

Results:
```
│ Error: Failed to retrieve Incus ImageServer
│ 
│   with incus_instance.instance1,
│   on main.tf line 21, in resource "incus_instance" "instance1":
│   21: resource "incus_instance" "instance1" {
│ 
│ The remote isn't a private server
╵
```

**Comment by maveonair** [comment]
This pull request adds support for starting OCI containers with Terraform: https://github.com/lxc/terraform-provider-incus/pull/111.

`incus_image` is a tricky one, as the Incus API client examines the image with the help of [skopeo](https://github.com/containers/skopeo), which must be installed on the system running Terraform or OpenTofu .I will address this after the PR has been merged at a later date.
