### ISSUE TITLE
No resource schema found for incus_instance_file when decoding prior state

### ISSUE THREAD

**Issue by austinried** [lxc/terraform-provider-incus#117]
I had `incus_instance_file` in my state previously, now after upgrade I have removed the files from my configuration but I get an error because it was removed in the new version.

```
╷
│ Warning: Missing resource schema from provider
│ 
│ No resource schema found for incus_instance_file when decoding prior state
╵
╷
│ Warning: Missing resource schema from provider
│ 
│ No resource schema found for incus_instance_file when decoding prior state
╵
╷
│ Error: no schema available for incus_instance_file.jump-user-authorized_keys while reading state; this is a bug in OpenTofu and should be reported
│ 
│ 
╵
╷
│ Error: no schema available for incus_instance_file.jump-admin-authorized_keys while reading state; this is a bug in OpenTofu and should be reported
│ 
│ 
╵
```

**Comment by stgraber** [comment]
Yes, this was intentional, see https://github.com/lxc/terraform-provider-incus/issues/88

We will keep supporting pushing files during instance creation (incus_instance) and will look at extending it a bit (https://github.com/lxc/terraform-provider-incus/issues/91).

**Comment by austinried** [comment]
I realized the removal was intentional but it wasn't clear to me how to resolve the problem from the error message, I couldn't `plan` or `apply` with this bad state. For others in the same boat, eventually I got it working again with:

```sh
tofu state rm <resource>
```
