### ISSUE TITLE
Add `source_file` to `incus_instance`

### ISSUE THREAD

**Issue by stgraber** [lxc/terraform-provider-incus#124]
This new instance source should take in a `path` variable which points to a backup file on the user's system.
The instance will then be created by having that backup uploaded to Incus (same as `incus import`).

**Comment by breml** [comment]
*Example:*

```Terraform
resource "incus_instance" "instance1" {
  name        = "test1"
  source_file = "/some/path/to/backup/file.tar.gz"
}
```

**Comment by stgraber** [comment]
I think project should be an option too.

For storage, it's a slightly odd one indeed.
What we could do to keep things better aligned with other instance sources is to allow the user to pass a root disk through devices. 

So we'd allow devices to be set, so long as it's got a single entry that's type=disk path=/ and has a pool key set and no other properties.

**Comment by breml** [comment]
You are right, `project` should be an option too and with this, also `remote` and `target` should be accepted.

What do you think about `file`? While it should be possible to implement this, I wonder if this is really ever a requirement, but I might be wrong about that one. Are you ok, if we omit it for now and only add it, when there is a known use case?

In regards to storage, I will look into your proposal.

**Comment by breml** [comment]
I looked at your proposal for the `storage` and I think, that this could work. I wonder though, if we really need to ask for the `path` property or if we can simply limit it to just `pool`. As far as I can tell, there is no validation, which would require `path` to be present.

**Comment by stgraber** [comment]
I just commented about that in the PR. We don't need the `path` property, but if we don't have it, it wouldn't be a valid root disk device for Incus so I think it would feel pretty off to folks and prevent them potentially sharing that device definition with an actual instance they may also have defined.
