### ISSUE TITLE
Add `source_file` to `incus_image`

### ISSUE THREAD

**Issue by stgraber** [lxc/terraform-provider-incus#125]
This new image source should take both a `metadata_path` (optional) and `data_path` variable which points to image file(s) on the user's system.

The image will then be created by pushing those files to the server in the same way that's done by `incus image import`.

**Comment by breml** [comment]
@stgraber I understand that the `data_path` would be used for two different things depending on `metadata_path` being provided or not. If `metadata_path` is **not** provided, we expect `data_path` to point to an *unified image*. In the other case, if `metadata_path` is provided, we expect `data_path` to point to a *rootfs tarball*, correct?
