### ISSUE TITLE
Remove the `limits` keyword in incus_instance (use `config` map instead)

### ISSUE THREAD

**Issue by stgraber** [lxc/terraform-provider-incus#134]
The `incus_instance` resource has a weird `limits` map which just gets converted to `limits.XYZ` config keys.

This is a very weird special case just for limits and just for instances as `incus_profile` uses traditional config keys instead.

It makes no sense to special case limits in that way, it doesn't actually save any space in the config (actually makes it longer) and the discrepancy with profiles is just confusing.

**Comment by maveonair** [comment]
So we should go from:

```hcl
resource "incus_instance" "instance1" {
  name  = "instance1"
  image = "images:debian/12"

  config = {
    "boot.autostart" = true
  }

  limits = {
    cpu = 2
  }
}
```

to

```hcl
resource "incus_instance" "instance1" {
  name  = "instance1"
  image = "images:debian/12"

  config = {
    "boot.autostart" = true
    "limits.cpu" = 2
  }
}
```

**Comment by stgraber** [comment]
yep!
