### ISSUE TITLE
Can't use `file` block on newly created virtual-machine 

### ISSUE THREAD

**Issue by austinried** [lxc/terraform-provider-incus#142]
Trying to create a new virtual machine that includes a `file` block but it keeps failed and saying the instance is not running:

```
│ Error: Failed to upload file to instance "wg-home"
│ 
│   with module.wg-home.incus_instance.cloud_instance,
│   on modules/cloud_instance/main.tf line 44, in resource "incus_instance" "cloud_instance":
│   44: resource "incus_instance" "cloud_instance" {
│ 
│ Could not create directories for file "/root/.ssh/authorized_keys": Instance is not running
```

This file block works fine with `container` type instances, only fails like this for a `virtual-machine` type. When I check the incus host, I find that the instance is indeed not running. However, after a manual `incus start wg-home` it appears to be running without issue (but without my authorized_keys that I wanted to copy over during creation).

Here's a snippet from my instance module, where I am setting what I think should cause the instance to automatically start when created:

```tf
  type             = var.type
  running          = true
  wait_for_network = true

  config = merge(
    {
      "boot.autostart" = true
    },
    var.type == "container" ? {
      "security.nesting" = true
    } : {},
    var.type == "virtual-machine" ? {
      "security.secureboot" = false
    } : {},
  )
```

Is this my issue or a bug? I don't know why for virtual machines it's not auto-starting for VMs but it is for containers.

**Comment by trunet** [comment]
`running` and `wait_for_network` defaults to `true` already.

I had this problem with old versions a couple of weeks/months ago.

Could you check if you're using an up2date incus server, incus client and terraform provider?

**Comment by austinried** [comment]
incus client/server: `6.0`
provider: `0.1.4`

I just upgraded incus to latest, 6.6, and encountered the same error. Maybe worth noting that I'm using OpenTofu 1.8.1. I also had this problem with an older version of the provider I think, I don't remember exactly what fixed it but I know it did work for a time and now it's broken again.

**Comment by maveonair** [comment]
> incus client/server: `6.0` provider: `0.1.4`
> 
> I just upgraded incus to latest, 6.6, and encountered the same error. Maybe worth noting that I'm using OpenTofu 1.8.1 (updating this to 1.8.3 also did not make a difference). I also had this problem with an older version of the provider I think, I don't remember exactly what fixed it but I know it did work for a time and now it's broken again.

There is a bug in the provider itself, but will be fixed with: https://github.com/lxc/terraform-provider-incus/pull/149
