### ISSUE TITLE
Publish to OpenTofu registry

### ISSUE THREAD

**Issue by maveonair** [lxc/terraform-provider-incus#23]
OpenTofu is now [GA](https://opentofu.org/blog/opentofu-is-going-ga/) and uses its own registry where we should publish our provider: https://github.com/opentofu/registry/

**Comment by stgraber** [comment]
https://github.com/opentofu/registry/blob/main/providers%2Fl%2Flxc%2Fincus.json

**Comment by adamcstephens** [comment]
Sure looks like it :) https://github.com/opentofu/registry/issues/116
