### ISSUE TITLE
No "remote" resource

### ISSUE THREAD

**Issue by antifob** [lxc/terraform-provider-incus#32]
Hi,

I was looking at this project referenced at [1] and noticed that there's no way to manage remotes. Something along the lines of

```
resource "incus_remote" "remote" {
  name = "myremote"
  url = "https://example.invalid/"
}
```

Regards

1: https://discuss.linuxcontainers.org/t/ansible-guidance-receiving-errors-when-using-lxd-container-plugin/18734

**Comment by stgraber** [comment]
Remotes aren't a server-side concept, it's just something that the `incus` command line tool implements as a way to interact with multiple servers.

**Comment by adamcstephens** [comment]
You can specify the remotes in the provider block: https://registry.terraform.io/providers/lxc/incus/latest/docs#specifying-multiple-remotes

Though ideally we'd refactor that at some point to have multiple incus provider blocks, as that's the more modern pattern with terraform.
