### ISSUE TITLE
Use another instance as the source of an instance (copy)

### ISSUE THREAD

**Issue by stgraber** [lxc/terraform-provider-incus#80]
This is somewhat related to #42 in that there are other ways to create instances.

A common one I find myself needing is the ability to create an instance from another one.

This would likely look something like:

```
resource "incus_instance" "this" {
    remote = "my-cluster"
    project = "my-project"
    target = "some-server"

    name = "foo"
    type = "container"

    source_instance {
        project = "source-project"
        name = "bar"
        snapshot = "snap0"
    }
}
```

**Comment by SpiffyEight77** [comment]
@stgraber 
I'm working on this feature.
Could you assign this task to me? 🙇🏻‍♂️

**Comment by stgraber** [comment]
I believe @maveonair may already have done some work on this one, let's see what he says first.

**Comment by SpiffyEight77** [comment]
> I believe @maveonair may already have done some work on this one, let's see what he says first.

Okay, waiting for the latest message.

**Comment by maveonair** [comment]
@SpiffyEight77 hey, I'm almost done with the feature. Do you mind taking another one of the milestone 1.0 issues: https://github.com/lxc/terraform-provider-incus/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0?

**Comment by SpiffyEight77** [comment]
@maveonair  Sorry for my late response.

It's okay and I will work on this #90.
