### ISSUE TITLE
Replace `incus_storage_volume_copy` with a `source` option on `incus_storage_volume`

### ISSUE THREAD

**Issue by stgraber** [lxc/terraform-provider-incus#90]
Similar to #89, it doesn't really make sense to have a resource for a one-time action.

Instead, `incus_storage_volume` already exists to define new volumes and should grow the ability to create a new volume from an existing one (or its snapshot).

We should probably use a `source` dict to handle that.

**Comment by SpiffyEight77** [comment]
@stgraber cc @maveonair Sorry to bother you at this moment.

I would like to work on this feature.

Could you assign it to me.

**Comment by SpiffyEight77** [comment]
@stgraber cc @maveonair 
I apologize for the delay. I will start working on this issue next week.
